apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/release-service/config/default?ref=9925a8f54df299d0484219a1a7f440332a586174

images:
  - name: quay.io/redhat-appstudio/release-service
    newName: quay.io/redhat-appstudio/release-service
    newTag: 9925a8f54df299d0484219a1a7f440332a586174

namespace: release-service
