apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=6cd78b65a0550fb367d5d0dbd3b12a1b6b2b4623
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=6cd78b65a0550fb367d5d0dbd3b12a1b6b2b4623

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: 6cd78b65a0550fb367d5d0dbd3b12a1b6b2b4623

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

components:
  - ../components/rh-certs
