apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - https://github.com/konflux-ci/service-provider-integration-operator/config/overlays/openshift_vault?ref=c70a5c769f17295a816d66982c3bc935eb83a72b

namespace: spi-system

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: c70a5c769f17295a816d66982c3bc935eb83a72b

patches:
  - target:
      kind: ConfigMap
      name: shared-environment-config
    path: config-patch.json
  - target:
      kind: Deployment
      name: spi-controller-manager
    path: operator-limits-patch.json
  - path: delete-shared-configuration-file.yaml
