apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/sprayproxy/config?ref=695281e3f6feb91b59c03a554ac2fb3b0334d130
  - pipelines-as-code-secret.yaml

images:
  - name: ko://github.com/konflux-ci/sprayproxy
    newName: quay.io/konflux-ci/sprayproxy
    newTag: 695281e3f6feb91b59c03a554ac2fb3b0334d130

patches:
  - path: change-backends.yaml
  - path: change-webhook-secret.yaml
  - path: bump-replicas.yaml
