apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-controller/config/default?ref=3c98f2d567f39fc7f0cb21e209969f5966d0028f

images:
- name: quay.io/konflux-ci/image-controller
  newName: quay.io/konflux-ci/image-controller
  newTag: 3c98f2d567f39fc7f0cb21e209969f5966d0028f

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
  - path: quaytoken.yaml
    target:
      name: quaytoken
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
