apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - https://github.com/konflux-ci/remote-secret/config/overlays/openshift_aws?ref=4f85a94a6b58e88f64bc9b4398cc706ffbd73038
  - https://github.com/konflux-ci/remote-secret/config/monitoring/prometheus?ref=4f85a94a6b58e88f64bc9b4398cc706ffbd73038
  - aws-credentials-external-secret.yaml

namespace: remotesecret

images:
  - name:  quay.io/redhat-appstudio/remote-secret-controller
    newName: quay.io/redhat-appstudio/remote-secret-controller
    newTag: 4f85a94a6b58e88f64bc9b4398cc706ffbd73038

patches:
  - target:
      kind: Deployment
      name: remote-secret-controller-manager
    path: operator-limits-patch.json
