apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spi-vault

resources:
  - https://github.com/konflux-ci/service-provider-integration-operator/config/vault/openshift?ref=c70a5c769f17295a816d66982c3bc935eb83a72b
