apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=2e6ce017a78dfc8a188e778e3f2d1c04f7d92357

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 2e6ce017a78dfc8a188e778e3f2d1c04f7d92357

namespace: project-controller
