apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/stonesoup-member-cluster?ref=18bafa73bba45c6a80a7f2abcd8e4bc3c1f7e91a
- ../../openshift-gitops/overlays/staging
- ../../base/external-secrets
- ../../base/monitoring
- authentication

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: 18bafa73bba45c6a80a7f2abcd8e4bc3c1f7e91a

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
